language: node_js
cache: yarn
node_js:
  - node
  - lts/*
script: yarn ci
after_success: yarn codecov
jobs:
  include:
    - stage: semantic-release
      if: branch = master
      node_js: node
      script:
        - yarn build
        - yarn release
